### ISSUE TITLE
Implement external file references to the Workflow parser

### ISSUE THREAD

**Issue by ricardozanini** [serverlessworkflow/sdk-go#14]
**What would you like to be added**:
In the specification, we have the possibility to add external files references in the workflow definition, for instance:

```json
{
  "id": "VetAppointmentWorkflow",
  "name": "Vet Appointment Workflow",
  "description": "Vet service call via events",
  "version": "1.0",
  "events": "features/vetappointmenteventrefs.json",
  "retries": "features/vetappointmentretries.json",
  "states": [
    {
      "name": "MakeVetAppointmentState",
      "type": "operation",
      "start": {
        "kind": "default"
      },
      "actions": [
        {
          "name": "MakeAppointmentAction",
          "eventRef": {
            "triggerEventRef": "MakeVetAppointment",
            "data": "{{ $.patientInfo }}",
            "resultEventRef":  "VetAppointmentInfo"
          },
          "actionDataFilter": {
            "dataResultsPath": "{{ $.appointmentInfo }}"
          },
          "timeout": "PT15M"
        }
      ],
      "onErrors": [
        {
          "error": "TimeoutError",
          "code": "500",
          "retryRef": "TimeoutRetryStrategy",
          "end": {
            "kind": "default"
          }
        }
      ],
      "end": {
        "kind": "default"
      }
    }
  ]
}
```

In this example, `retries` and `events` are defined externally to the main file. The SDK supposed to incorporate those while parsing the main definition.

**Why is this needed**:
To conform with the specification.

**Comment by iwita** [comment]
Hello,
So I suppose there should be implemented the following:
1. Recognize directory/file strings using some sort of regexp
2. Parse the encapsulated file (using recursion in case of additional nested files)
3. Replace them in the parsed workflow

Am I right?

**Comment by ricardozanini** [comment]
Hi!

> Recognize directory/file strings using some kind of regexp

You can unmarshal the workflow into `RawJson` first and use a map to access `functions`, `events`, or `retries`, which is the types that can have an external reference

> Parse the encapsulated file (using recursion in case of additional nested files)

I don't think we will have nested files for `functions`, `events`, and `retries`. Only for Subflows. But for this state type, we should handle it differently, maybe in another issue. See for example https://github.com/serverlessworkflow/specification/blob/0.5.x/schema/functions.json

> Replace them in the parsed workflow

:+1: 

One remark only is that the nested references should be read from the relative path unless it starts with `file://`. @tsurdilo do we support URI on `functions`, `events`, and `retries` fields? All I see is that they are references for the object itself.

**Comment by tsurdilo** [comment]
@ricardozanini if they are string we currently define as "URI pointing to a resource containing json/yaml function/events/retries definitions".

We just use classpath atm in the java sdk for lookup but should prob update to use uri :) I think it's fine to define it as you guys wish for now and then enhance later if needed

**Comment by ricardozanini** [comment]
@tsurdilo thanks for the clarification. For this use case specifically, I believe we might need some tweaks in the unmarshalling process. The generated code attributes an array of events to the events field in the workflow. I believe the "RawJson" in our case should do. 

@iwita We might need to have a new structure to parse the workflow first into functions, events and retries into RawJson. Then verify if it's a URI to parse these objects first.

**Comment by iwita** [comment]
Hi @ricardozanini and @tsurdilo,
Thank you for your suggestions and help. 
I checked the code and I am back with some suggestions:

1. In order to be able to identify any errors from the full workflow unmarshalling, I would propose to change the WorkflowCommon altering the json tags of the needed fields.
``	
Events           []Eventdef `json:"-"`      
``
This way, those fields will be ignored during the initial workflow parsing.

2. Furthermore, by parsing the json file into json.RawMessage and then unmarshalling the desired fields (using a map) into a string we will be able to identify if we have a string or other interface. In the first case, we will check the cases of URI, relative or absolute path, and then will unmarshal the required fields (functions, events, retries) from the respective files. Else, we will unmarshal those fields explicitly from the map[string]RawMessage.

P.S.1  I will submit a new PR today or tomorrow if you agree with the above.  
P.S.2  There is no current definition of Retries type.
P.S.3  Should I implement unit testing or there would be some other issue opened?

**Comment by ricardozanini** [comment]
Hi @iwita ! Many thanks for your suggestions!

> In order to be able to identify any errors from the full workflow unmarshalling, I would propose to change the WorkflowCommon altering the json tags of the needed fields.

I believe it's better to implement a `UnmarshalJSON` function to `EventDef`, `FunctionDef`, and `RetryDef`, this way we can fetch for the URI and unmarshal it recursively. The problem is that the tool we are using to generate code is already generating the functions for these types. We will have to configure the tool to not generate it for these types somehow.

> Furthermore, by parsing the json file into json.RawMessage and then unmarshalling the desired fields (using a map) into a string we will be able to identify if we have a string or other interface. In the first case, we will check the cases of URI, relative or absolute path, and then will unmarshal the required fields (functions, events, retries) from the respective files. Else, we will unmarshal those fields explicitly from the map[string]RawMessage.

This can be done on the respective `UnmarshalJSON` functions

>  I will submit a new PR today or tomorrow if you agree with the above.

That's great! :+1: 

> There is no current definition of Retries type.

Yeah, I just noticed that indeed. This is weird, I need to take a careful look into the tooling that generated the code. I just quickly tried generating it again, and the `Retries` definition is not there.

>  Should I implement unit testing or there would be some other issue opened?

Oh please, yes, implement them :)

**Comment by iwita** [comment]
Hello,

> I believe it's better to implement a UnmarshalJSON function to EventDef, FunctionDef, and RetryDef, this way we can fetch for the URI and unmarshal it recursively. The problem is that the tool we are using to generate code is already generating the functions for these types. We will have to configure the tool to not generate it for these types somehow.

Since `UnmarshalJSON` implements the json.Unmarshaler for each respective field (`Eventdef`, `Functiondef` ), we needed a wrapper type in order to handle slices of (`Eventdef`, `Functiondef` ). Otherwise, by modifying the `Eventdef` handler, `json.Unmarshal()` (for the workflow type), didn't even reach `Eventdef` type, because it returned an error when detecting a `string` instead of a `[]Eventdef`.

While I tried to figure out how to do it this way, I ended up with an ugly solution.


```golang
func FromJSONSourceHelper(source []byte) (workflow *model.Workflow, err error) {
	var m map[string]json.RawMessage
        // unmarshal the source into a map in order to get discrete fields
	if err := json.Unmarshal(source, &m); err != nil {
		return nil, err
	}
	nestedCandidates := []string{"events", "retries", "functions"}
	var s string
	for _, v := range nestedCandidates {
		if err := json.Unmarshal(m[v], &s); err != nil {
			if _, ok := m[v]; !ok {
				continue
			}
			// It's not a string
			return FromJSONSource(source)
		}
		// It's a string
		var fileBytes []byte
		if fileBytes, err = getBytesFromFile(s); err != nil {
			return nil, err
		}
		if err = json.Unmarshal(fileBytes, &m); err != nil {
			return nil, err
		}
	}
	bytes, err := json.Marshal(m)
	return FromJSONSourceHelper(bytes)
}
```

**Comment by ricardozanini** [comment]
Hey @iwita !

yes, since the structure is an array of attributes and not a string, the unmarshal will complain. That's why I said that we might need to change the [`UnmarshalJSON`](https://github.com/serverlessworkflow/sdk-go/blob/master/model/zz_generated.types_events.go#L104-L119) function and unmarshal to `RawJson` first, check if it's a string first. More or less what you did in the example.

This is the unmarshal function I'm referring to:
https://github.com/serverlessworkflow/sdk-go/blob/master/model/zz_generated.types_events.go#L104-L119

The biggest problem is that this function is generated, that's why we will need to configure the tooling that generates it to not do it.

**Comment by iwita** [comment]
Hi all,

I searched for the `model/zz_*` files generation process. The https://github.com/atombender/go-jsonschema repository is used in order to create the schema for each type. It does not seem to produce any other files.

When running the `hack/generate-spec-types.sh` script there are several warnings occurring.
1.  The Events, Functions types are created as map[string]interface{}, since in the json definitions (https://github.com/serverlessworkflow/specification/blob/master/schema/workflow.json) those types are declared either as strings either as an array of objects. 
2. When I tried to add the retries.json file, there are errors occurring related to a parameter that is float instead of integer. More specifically, while there is a float value in the field Type.Parameters.Minimum, which can be found here: https://github.com/atombender/go-jsonschema/blob/master/pkg/schemas/model.go#L78, the script errors for not being an integer.

Regarding this issue, I changed the types.go file, in order to isolate []Eventdef and []Function (by removing it from WorkflowCommon type) similar to []State. This way, we are able to parse those types independently from here: https://github.com/serverlessworkflow/sdk-go/blob/master/model/unmarshal_json.go#L23-L53.

**Comment by ricardozanini** [comment]
Great additions, @iwita 

Regarding this:

> When I tried to add the retries.json file, there are errors occurring related to a parameter that is float instead of integer. More specifically, while there is a float value in the field Type.Parameters.Minimum, which can be found here: https://github.com/atombender/go-jsonschema/blob/master/pkg/schemas/model.go#L78, the script errors for not being an integer.

Reading this part of the code, I believe they follow the spec and we might need to change our field to float instead. @tsurdilo wdty?

https://github.com/serverlessworkflow/specification/blob/master/schema/retries.json#L37-L38

**Comment by iwita** [comment]
Thank you @ricardozanini 

> Reading this part of the code, I believe they follow the spec and we might need to change our field to float instead. @tsurdilo wdty?

The script complains about the jitter minimum field.
https://github.com/serverlessworkflow/specification/blob/master/schema/retries.json#L43-L44

**Comment by tsurdilo** [comment]
I think in jsonschema "number" represents both integers and floats. Maybe best to just use float on the sdk side as thats superset?

**Comment by ricardozanini** [comment]
@tsurdilo @iwita I believe I covered this problem in this PR: https://github.com/serverlessworkflow/specification/pull/193

**Comment by ricardozanini** [comment]
> Thank you @ricardozanini
> 
> > Reading this part of the code, I believe they follow the spec and we might need to change our field to float instead. @tsurdilo wdty?
> 
> The script complains about the jitter minimum field.
> https://github.com/serverlessworkflow/specification/blob/master/schema/retries.json#L43-L44

jitter or `maxAttempts`? Since the last one was in integer format and float was expected.

**Comment by iwita** [comment]
> @tsurdilo @iwita I believe I covered this problem in this PR: serverlessworkflow/specification#193

Now there is an additional error occurring in `hack/generate-spec-types.sh`. This time for the `workflow.json` because it does not accept once again the minimum field. 


`` --> Generating specification types    `` 
`` gojsonschema: Loading /tmp/serverlessworkflow/schema/common.json      `` 
`` gojsonschema: Loading /tmp/serverlessworkflow/schema/events.json    `` 
`` gojsonschema: Warning: Multiple types map to the name "Metadata"; declaring duplicate as "Metadata_1" instead`` 
`` gojsonschema: Warning: Object type with no properties has required fields; skipping validation code for them since we don't know their types`` 
`` gojsonschema: Loading /tmp/serverlessworkflow/schema/functions.json`` 
`` gojsonschema: Warning: Object type with no properties has required fields; skipping validation code for them since we don't know their types`` 
`` gojsonschema: Loading /tmp/serverlessworkflow/schema/workflow.json`` 
`` gojsonschema: Failed: json: cannot unmarshal number 0.0 into Go struct field Type.definitions.properties.minimum of type int
``

Do you think there is any bug in the generator?

**Comment by ricardozanini** [comment]
I'll revert them back to 0 instead. `0.0` and `0` seems the same to me. Might be a bug in their side, but I'd rather keep `0`. @tsurdilo would you be angry if we revert from `0.0` to `0` in the spec?

**Comment by tsurdilo** [comment]
@ricardozanini that's fine. let's go for it.

**Comment by iwita** [comment]
Then I hope it does not complain for the maximum value as well (which is 1.0) in the `jitter` case.

**Comment by ricardozanini** [comment]
@iwita can you test with this PR instead? https://github.com/serverlessworkflow/specification/pull/195
